name: Deploy Hexo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Hexo
        run: |
          npm install hexo-cli -g
          npm install

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global user.name "bcuej"
          git config --global user.email "xiexy235@mail2.sysu.edu.cn"
          npx hexo clean
          npx hexo generate
          npx hexo deploy --repo https://$GIT_USER@github.com/bcuej/bcuej.github.io.git
