name: Deployment

on:
  push:
    branches: [main]

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 使用 Node.js 18 LTS 版本

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc  # 安装 pandoc

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm install
        hexo clean
        hexo generate

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        keep_files: true
